using System.Security.Cryptography;
using Exo.Helpers;

namespace Exo.Security;

public enum ScriptTrustPolicy
{
    ShippedManifest,
    AppGeneratedNetwork,
    /// <summary>Compact elevated HKLM pack generated by NativeApplyService.</summary>
    AppGeneratedNative
}

internal static partial class ShippedScriptManifest
{
    public static ShippedArtifactClosureVerification VerifyClosure(string path) =>
        ShippedArtifactClosureVerifier.VerifyManagedRoots(
            PathHelper.ScriptsRoot,
            PathHelper.WorkingScriptsDir,
            path,
            Entries);

    public static (bool Ok, string Message) Verify(string path, ScriptTrustPolicy policy)
    {
        if (policy == ScriptTrustPolicy.AppGeneratedNetwork)
            return VerifyGeneratedNetworkScript(path);
        if (policy == ScriptTrustPolicy.AppGeneratedNative)
            return VerifyGeneratedNativeScript(path);

        var closure = VerifyClosure(path);
        return (closure.Ok, closure.Message);
    }

    private static (bool Ok, string Message) VerifyGeneratedNetworkScript(string path)
    {
        try
        {
            var full = Path.GetFullPath(path);
            var tempRoot = Path.GetFullPath(Path.GetTempPath()).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
            var name = Path.GetFileName(full);
            var valid = full.StartsWith(tempRoot, StringComparison.OrdinalIgnoreCase) &&
                        name.StartsWith("exo-net-", StringComparison.OrdinalIgnoreCase) &&
                        name.EndsWith(".ps1", StringComparison.OrdinalIgnoreCase);
            return valid
                ? (true, name)
                : (false, "Generated elevated scripts are restricted to Exo's network transaction path.");
        }
        catch (Exception ex)
        {
            return (false, $"Generated script path could not be validated: {ex.Message}");
        }
    }

    private static (bool Ok, string Message) VerifyGeneratedNativeScript(string path)
    {
        try
        {
            var full = Path.GetFullPath(path);
            var tempRoot = Path.GetFullPath(Path.GetTempPath()).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
            var name = Path.GetFileName(full);
            var valid = full.StartsWith(tempRoot, StringComparison.OrdinalIgnoreCase) &&
                        name.StartsWith("exo-native-", StringComparison.OrdinalIgnoreCase) &&
                        name.EndsWith(".ps1", StringComparison.OrdinalIgnoreCase);
            return valid
                ? (true, name)
                : (false, "Generated elevated scripts are restricted to Exo's native apply transaction path.");
        }
        catch (Exception ex)
        {
            return (false, $"Generated native script path could not be validated: {ex.Message}");
        }
    }
}
