[CmdletBinding()]
param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'Exo\Security\ShippedScriptManifest.g.cs')
)

$ErrorActionPreference = 'Stop'
$scriptsRoot = Join-Path $Root 'Exo\Scripts'
if (-not (Test-Path -LiteralPath $scriptsRoot -PathType Container)) {
    throw "Scripts root not found: $scriptsRoot"
}

$files = Get-ChildItem -LiteralPath $scriptsRoot -Recurse -File | Where-Object {
    $relative = [IO.Path]::GetRelativePath($scriptsRoot, $_.FullName).Replace('\', '/')
    $relative -notmatch '(^|/)Placeholders/' -and
    $relative -notmatch '^Discord/kit/tools/discord-modules/' -and
    $relative -notmatch '^Discord/kit/tools/pwsh/' -and
    $relative -notmatch '^Discord/kit/downloads/' -and
    $relative -notmatch '^Discord/kit/logs/' -and
    $relative -notmatch '^Discord/kit/tools/(desktop|equicord)\.asar$' -and
    $relative -notmatch '^Discord/kit/tools/(DiscordSetup|Equilotl).*\.exe$'
} | Sort-Object FullName

$body = [Text.StringBuilder]::new()
[void]$body.AppendLine('// <auto-generated />')
[void]$body.AppendLine('namespace Exo.Security;')
[void]$body.AppendLine()
[void]$body.AppendLine('internal static partial class ShippedScriptManifest')
[void]$body.AppendLine('{')
[void]$body.AppendLine('    private static readonly IReadOnlyDictionary<string, ManifestEntry> Entries =')
[void]$body.AppendLine('        new Dictionary<string, ManifestEntry>(StringComparer.OrdinalIgnoreCase)')
[void]$body.AppendLine('        {')
foreach ($file in $files) {
    $relative = [IO.Path]::GetRelativePath($scriptsRoot, $file.FullName).Replace('\', '/')
    $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash
    $escaped = $relative.Replace('"', '\"')
    [void]$body.AppendLine(('            ["{0}"] = new({1}L, "{2}"),' -f $escaped, $file.Length, $hash))
}
[void]$body.AppendLine('        };')
[void]$body.AppendLine('}')

$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Path $parent -Force | Out-Null
[IO.File]::WriteAllText($OutputPath, $body.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "Generated $($files.Count)-entry script manifest: $OutputPath"
