[CmdletBinding()]
param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'Exo\Security\ShippedScriptManifest.g.cs')
)

$ErrorActionPreference = 'Stop'
$scriptsRoot = Join-Path $Root 'Exo\Scripts'
if (-not (Test-Path -LiteralPath $scriptsRoot -PathType Container)) {
    throw "Scripts root not found: $scriptsRoot"
}

$files = Get-ChildItem -LiteralPath $scriptsRoot -Recurse -File | Where-Object {
    $relative = [IO.Path]::GetRelativePath($scriptsRoot, $_.FullName).Replace('\', '/')
    $relative -notmatch '(^|/)Placeholders/' -and
    $relative -notmatch '^Discord/kit/tools/discord-modules/' -and
    $relative -notmatch '^Discord/kit/tools/pwsh/' -and
    $relative -notmatch '^Discord/kit/downloads/' -and
    $relative -notmatch '^Discord/kit/logs/' -and
    $relative -notmatch '^Nvidia/tools/' -and
    $relative -notmatch '^Discord/kit/tools/(desktop|equicord)\.asar$' -and
    $relative -notmatch '^Discord/kit/tools/(DiscordSetup|Equilotl).*\.exe$'
} | Sort-Object FullName

function Get-ManifestBytes([IO.FileInfo]$File) {
    $textExtensions = @('.ps1', '.json', '.ini', '.md', '.c', '.def', '.css', '.txt', '.vbs')
    $isText = $textExtensions -contains $File.Extension.ToLowerInvariant() -or
        $File.Name -in @('VERSION', 'PROFILE_VERSION')
    if (-not $isText) { return [IO.File]::ReadAllBytes($File.FullName) }

    # Git stores text with LF while Windows working trees commonly use CRLF.
    # Integrity is about shipped script content, not checkout line-ending policy.
    $canonical = [IO.File]::ReadAllText($File.FullName).Replace("`r`n", "`n").Replace("`r", "`n")
    return [Text.UTF8Encoding]::new($false).GetBytes($canonical)
}

$body = [Text.StringBuilder]::new()
[void]$body.AppendLine('// <auto-generated />')
[void]$body.AppendLine('namespace Exo.Security;')
[void]$body.AppendLine()
[void]$body.AppendLine('internal static partial class ShippedScriptManifest')
[void]$body.AppendLine('{')
[void]$body.AppendLine('    private static readonly IReadOnlyDictionary<string, ManifestEntry> Entries =')
[void]$body.AppendLine('        new Dictionary<string, ManifestEntry>(StringComparer.OrdinalIgnoreCase)')
[void]$body.AppendLine('        {')
foreach ($file in $files) {
    $relative = [IO.Path]::GetRelativePath($scriptsRoot, $file.FullName).Replace('\', '/')
    $bytes = Get-ManifestBytes $file
    $hash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes))
    $escaped = $relative.Replace('"', '\"')
    [void]$body.AppendLine(('            ["{0}"] = new({1}L, "{2}"),' -f $escaped, $bytes.LongLength, $hash))
}
[void]$body.AppendLine('        };')
[void]$body.AppendLine('}')

$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Path $parent -Force | Out-Null
[IO.File]::WriteAllText($OutputPath, $body.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "Generated $($files.Count)-entry script manifest: $OutputPath"
